### ISSUE TITLE
Just a query - Is this a port of MR library from the coursera course Modern Robotics?

### ISSUE THREAD

**Issue by VarLad** [ferrolho/ModernRoboticsBook.jl#2]
Not an issue 
Just asking whether this is a port of the MR library from the [Coursera Course](https://www.coursera.org/learn/modernrobotics-course1/supplement/htN7x/welcome-to-the-specialization).

**Comment by ferrolho** [comment]
Yes, that is correct. This repository is a Julia version of the library https://github.com/NxRLab/ModernRobotics.
